# Generated by Django 3.1.5 on 2021-01-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luna_coding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photoprofile',
            new_name='photo_profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
